#!/bin/sh

# Create and post raw waveform plots

RUN=$1
EVT=$2
if [ -z "$EVT" ]; then
  echo Usage: $0 RUN EVT
  exit 0
fi
FRUN=$(formatInt $RUN)
FEVT=$(formatInt $EVT)
FRAN=000000-001000

CFG=noSuchConfig
if [ $RUN -ge 11805 ]; then
  CFG=coldbox2021warm
elif [ $RUN -eq 11795 ]; then
  CFG=coldbox2019warm
else
  echo Configuration not set for run $RUN
  exit 1
fi

FCLDIR=run_dataprep_apa7/$CFG/addWfRaw
EVTDIR=np04_run${FRUN}_evts${FRAN}/event$FEVT
RUNDIR=$FCLDIR/$EVTDIR
WWWDIR=$HOME/wwwdune/protodune/apa7/data/wfraw
OUTDIR=$WWWDIR/$CFG/run$FRUN/event$FEVT

if [ -r $OUTDIR ]; then
  echo Web dir already exists: $OUTDIR
  exit 1
fi
echo Output dir: $OUTDIR

if [ -r $RUNDIR ]; then
  echo Processing dir exists: $RUNDIR
else
  echo Processing data...
  duneproc $FCLDIR $EVTDIR
fi

if ! ls $RUNDIR/*.png 2>&1 1>/dev/null; then
  echo Run plots not found at $RUNDIR
  exit 1
fi

if [ ! -d $WWWDIR ]; then
  echo Base output dir not found: $WWWDIR
  exit 1
fi
mkdir -p $OUTDIR
cp $RUNDIR/*.png $OUTDIR
makeIndex $OUTDIR
makeIndex $OUTDIR/.. k
makeIndex $OUTDIR/../.. k
makeIndex $OUTDIR/../../.. k
